{% set version = "1.4-24" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multcomp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multcomp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multcomp/multcomp_{{ version }}.tar.gz
  sha256: 7e64ed3013620772f802863704f9530eabdf62c1a9df936c3e42636d344fb411

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-th.data >=1.0_2
    - r-codetools
    - r-mvtnorm >=1.0_10
    - r-sandwich >=2.3_0
    - r-survival >=2.39_4
  run:
    - r-base
    - r-th.data >=1.0_2
    - r-codetools
    - r-mvtnorm >=1.0_10
    - r-sandwich >=2.3_0
    - r-survival >=2.39_4

test:
  commands:
    - $R -e "library('multcomp')"           # [not win]
    - "\"%R%\" -e \"library('multcomp')\""  # [win]

about:
  home: http://multcomp.R-forge.R-project.org The publishers web page is http://www.crcpress.com/product/isbn/9781584885740
  license: GPL-2.0-only
  summary: Simultaneous tests and confidence intervals for general linear hypotheses in parametric models, including  linear, generalized linear, linear mixed effects, and survival models. The package includes demos reproducing analyzes presented in the book "Multiple Comparisons Using R" (Bretz, Hothorn,  Westfall, 2010,
    CRC Press).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: multcomp
# Title: Simultaneous Inference in General Parametric Models
# Version: 1.4-10
# Date: 2019-03-04
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"),  email = "Torsten.Hothorn@R-project.org", comment = c(ORCID = "0000-0001-8301-0471")),  person("Frank", "Bretz", role = "aut"),  person("Peter", "Westfall", role = "aut"), person("Richard M.", "Heiberger", role = "ctb"), person("Andre", "Schuetzenmeister", role = "ctb"), person("Susan", "Scheibe", role = "ctb"))
# Description: Simultaneous tests and confidence intervals for general linear hypotheses in parametric models, including  linear, generalized linear, linear mixed effects, and survival models. The package includes demos reproducing analyzes presented in the book "Multiple Comparisons Using R" (Bretz, Hothorn,  Westfall, 2010, CRC Press).
# Depends: stats, graphics, mvtnorm (>= 1.0-10), survival (>= 2.39-4), TH.data (>= 1.0-2)
# Imports: sandwich (>= 2.3-0), codetools
# Suggests: lme4 (>= 0.999375-16), nlme, robustbase, coin, MASS, foreign, xtable, lmtest, coxme (>= 2.2-1), SimComp, ISwR, tram (>= 0.2-5)
# URL: http://multcomp.R-forge.R-project.org The publishers web page is http://www.crcpress.com/product/isbn/9781584885740
# LazyData: yes
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2019-03-04 08:20:51 UTC; hothorn
# Author: Torsten Hothorn [aut, cre] (<https://orcid.org/0000-0001-8301-0471>), Frank Bretz [aut], Peter Westfall [aut], Richard M. Heiberger [ctb], Andre Schuetzenmeister [ctb], Susan Scheibe [ctb]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-03-05 13:00:03 UTC
