appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OcAdAjt1317WrdCWTeZovAMK7pk3nnIlyWoKweTqYR+zGSb5bmFBF2cMgn87EyiSQE5DNYhWoVvewj6fGKOpTIsTEWs3Kuht0nfTzD6hE1dH67fNldRq8hFCdBZVJ+pFfZItM9miOvl52L4XPSBfB/71FQOMSAK49Snn2cMCqnR7iCa6RObIUiqaBYKiTVoXfjQ/ZeLmtbgJuspBwvIRSY0AbmYqgrccD/WY7BSbWfpylmbnZn8bG3DsG0Dre9EOjCN/6vdB+EGohOmjYAVelYYm4kEEIqnf1/1Wg8GJbv3LfxNd1P9Kp+96w9bsTjBP4P2PMickULD+FS78V39x+gyPAWx+w26yXuAKUL1uiaZ0LJflz63wQ41HkDzRE3bMTgM7GRNO0sEiA6yJMsXxEA+t/R7x4NS9ebOeWBMk4bmAY2TXMFp/9Jx/IFR//Svv8N+lqCywVSglA8F15xYmlQI/GWT0I+6sZfIgZPmDSgZ45kJZs+gf41PanLxVoG7p3N96TLeEGd9+T0iYzrIkJvK9AxR4SEkdguCqTgPqXXBhjcVoIEQ6Iq6goEoneJ3UyvbjceTnNpgO+66nehygFXxHYSIYbf3MCOglKhFE13eUD7y9B0Z4lWuTbOK6wijR3hbfOz0eloxn1o6kOX4PfZs5TEsdVtfrrwLVoowHBcY=}
